### ISSUE TITLE
Slotcar Error related to names

### ISSUE THREAD

**Issue by TheConstructAi** [open-rmf/roscon_workshop#16]
## Bug report
gzserver-20] [ERROR] [1668788235.104061377] [gazebo_ros_node]: Found multiple nodes with same name: /slotcar. This might be due to multiple plugins usingthe same name. Try changing one of the the plugin names or use a different ROS namespace. This error might also result from a custom plugin inheriting from another gazebo_ros plugin and the custom plugin trying to access the ROS node object hence creating multiple nodes with same name. To solve this try providing the optional node_name argument in gazebo_ros::Node::Get() function.
[gzserver-20] [Err] [Model.cc:1160] Exception occured in the Load function of plugin with name[slotcar] and filename[libslotcar.so]. This plugin will not run.

When running the example, it jumps this error.
Whihc branch or repo of rmf are you using fo this to work?

Because this is solved by giving unique names to the plugin in Gazebo, but it seems here that you did it without that issue.

### Required information:

- Operating system and version: Ubuntu 22
- OpenRMF installation type: From source
- OpenRMF version or commit hash: main
- ROS installation type: Humble

### Description of the bug

when launching this:

ros2 launch roscon_gz_classic workshop.launch.xml

It appears the mentioned error and nothing loads, not the map, nor anything.
It been doesn't find the needed models in gazebo

**Comment by Yadunund** [comment]
Same solution https://github.com/open-rmf/roscon_workshop/issues/17#issuecomment-1321541086

Let us know if you still have any problems. Feel free to try out the virtual box linked in the README. It should contain a workspace with the right setup.

**Comment by Yadunund** [comment]
Closing issue but feel free to reopen if the problem exists after updating the repos pkgs.
