### ISSUE TITLE
[Other issue]: What is the password for VirtualBox image ?

### ISSUE THREAD

**Issue by jigang-duan** [open-rmf/roscon_workshop#27]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

What is the password for VirtualBox image ?

**Comment by Yadunund** [comment]
Refer to the linked line about [preparation document for this workshop](https://github.com/open-rmf/roscon_workshop#roscon_workshop) in the README.
